### ISSUE TITLE
Save credentials

### ISSUE THREAD

**Issue by felix-hilden** [felix-hilden/spotipy#124]
From #117, now we read configuration. Should we also save it?

I'm thinking: It's a valid use case, but. Compared to the usage of loading credentials, it's low. And once you do it, it doesn't have to be changed. So I'm not sure. It could be implemented though, because the user refresh token is expected to change, even though it might be rare in practice.

Maybe not for environment variables, because they cannot be set globally, so it would vanish after leaving the process. One might as well use variables for that. But for configfiles it might be worth the effort.

@marioortizmanero I hear you've made a comprehensive configuration manager. Thoughts? How did you go about it?

**Comment by marioortizmanero** [comment]
Saving configuration is a great idea now that it can be read. That way, it can be kept persistently (unlike environment variables) and it's a much better alternative to Plamere's `.spotipy-cache`.

My configuration manager is probably more complex than what this module needs: it mixes `argparse` and `configparse`, supports multiple types (you probably only need `str`), maintains changes in the object set with `__setattr__`... but it may be of help: https://github.com/marioortizmanero/spotify-music-videos/blob/next/vidify/config.py.

My options are listed in a custom-made Enum. This is better than using a class with dataclasses, mainly because you can iterate it easily (actually you might not need to iterate it, so you can go with whatever option you prefer). It's like a mix between a `struct` and an `enum` (in C). Inside each option, I save information about it: its name (as the variable name, which I can access with `.name`), the default value, the type, and the config section (maybe you want to use something other than `[Defaults]`).

Then, I have a `Config` class with the actual values of the `Options` enum. It defines a `read_file` and `write_file` so that the returned value is of the type listed in its `Options`, and it's written in the section defined there. I can later use these functions in the custom `__getattr__` and `__setattr__` to automatically read or write the option from/to the config file.

If you have any questions you can go ahead and ask. My modue can definitely be improved though, and it needs a strong suite of tests because many things can go wrong.

**Comment by felix-hilden** [comment]
Thanks for your thoughts! I had a look, and actually your `Config.write_file` could do by itself as `config_to_file(file: str, section: str, values: dict)`. Then `values` would map config names to values, but it has a problem. It would be nice to be able to write configuration without knowing the variable names. So maybe a tuple or list of length 3 or 4 could also be accepted, and that would be mapped to the same order that the read functions return values in.

**Comment by felix-hilden** [comment]
Let's scratch that. Better to only specify a tuple and use the names that are specified in the module. Then discard all `None` values.
