### ISSUE TITLE
consider setting default market to None instead of 'from_token'

### ISSUE THREAD

**Issue by bugflush** [felix-hilden/spotipy#58]

**Comment by felix-hilden** [comment]
Thanks again for the hunting!

This was in consideration when I wrote the client. I think the most common use-case is retrieving songs and albums for an actual Spotify user to see. If there is no market specified, unplayable tracks could be returned. If someone wants to search for all possible tracks, they can specify "no market". I think the default should be `from_token`. If you have any concerns regarding that decision, please do voice them. I'm open to changing it for a good reason.

**Comment by bugflush** [comment]
- default should work all cases. for example only with application token
- default should return what user asked and not something else.
 (for example: s.track('322oaXi0bLkuaNMcZMh52r').id returns '4Tq2fWpX1nLCkMSOPkYb1Y' )

**Comment by felix-hilden** [comment]
I'm convinced, mainly because of the application token thing, that's a good point!

You have been so helpful and generous filing all these issues, thank you! I'd love to have you in the contributors section. Would you mind sending a pull request on this one? I know it's a minor fix, tests wouldn't even need to be changed as they are explicit about the market.

I'm thinking each market/country argument should be `market: str = None` instead of `market: Union[str, None] = 'from_token'` and the docstring should be `An ISO 3166-1 alpha-2 country code or 'from_token'`, removing the `None` that there is currently.

Let me know if you are available, otherwise I'll fix it right away.

**Comment by bugflush** [comment]
search() still has 'from_token' default
