### ISSUE TITLE
fix errors reported by mypy

### ISSUE THREAD

**Issue by bugflush** [felix-hilden/spotipy#64]
Found 75 errors in 23 files (checked 43 source files)

**Comment by felix-hilden** [comment]
I have no experience with other implementations of Python apart from C-python. So I'm not sure of the impact of trying to support them is, but I'll look into it. One would expect things to function the same across implementations of course.

**Comment by felix-hilden** [comment]
Yeah, I tested it out, but at a quick glance none of the errors were valid. Seems like a bad move. For example, all models that had a `None` default were errors because a none type is of course incompatible with whatever the field is supposed to be.

**Comment by bugflush** [comment]
for example:
spotipy/model/user.py:12: error: Incompatible types in assignment (expression has type "None", variable has type "Followers")

I think Optinal should be used:
    followers: Optional[Followers] = None

(and also document  on what situation followers is None?)

**Comment by felix-hilden** [comment]
I created an issue of the model types. They need some work. But here are some more points of concern, just a few of the first ones, and I can't see the reason to fix them. That's just a whole lot of unnecessary type hints.

- `client/browse/__init__:226` : Incompatible types in assignment (str -> int) where a simple dict is populated. `seed_artists` surely is and is supposed to be a string. This goes for the other assignments as well.
- `client/artist:73` : Incompatible types in assignment when parsing `include_groups` if they are not none. Having another variable would require an `else: var = None` statement and even then `mypy` would issue an error when assigning none to a string.
- `client/player` : missing return statements. They are not needed, because `None` should be returned. Incompatible dict types in 166, which again are not valid complaints.

**Comment by bugflush** [comment]
Maybe use "# type: ignore" then?
https://mypy.readthedocs.io/en/latest/common_issues.html#spurious-errors-and-locally-silencing-the-checker

**Comment by felix-hilden** [comment]
On every such line? I'm sorry, it's a no. I'm all for using a static checker to find potential flaws but the code itself shouldn't bend to a linter's will. Maybe that's just me, but what a mess.
