### ISSUE TITLE
Client methods requiring user authentication

### ISSUE THREAD

**Issue by felix-hilden** [felix-hilden/spotipy#90]
Many endpoints that require user authentication are prefixed by `current_user`. Others, like playlist and playback endpoints don't have that prefix. The naming should be consistent.

Having the prefix in every endpoint would be consistent but would also lead to impossibly long method names like `current_user_playlist_cover_image_upload`. And with some endpoints, like the playback ones, it is quite obvious that they require user authentication.

I think if there is no ambiguity whether a user account is needed, the prefix should be removed. And if it leads to bad method names, they should be renamed. But there is some value in keeping names consistent across an API.

By API:
- Album, Artist, Browse, Track: no user authentication needed
- Follow: actions like `follow` and `unfollow`, or getting `followed_artists` are clear, but e.g. `artists_is_following` would be a bit confusing
- Library: `current_user` could be replaced with `saved` (like `saved_albums`), which would have the advantage of being able to discover the library API more easily
- Player: unambiguously related to a user
- Playlist: unambiguously related to a user or a shared playlist, except `current_user_playlists`
- Misc: top artists and tracks are ambiguous, they could retain the prefix

If we want to be cute about it, we could even check if the current token is a user token and throw an error early. This could be implemented as a simple decorator on every required method.

**Comment by felix-hilden** [comment]
I'm pretty sure of this:
- Library: `current_user -> saved`
- Playlist, Top: prefix left as it is

But I'd like a second opinion on the Follow API.. 😄 @marioortizmanero whaddaya think? How would you name these?
- `playlist_is_following(playlist_id, user_ids)`
- `current_user_playlist_follow(playlist_id)`
- `current_user_followed_artists()`
- `current_user_artists_is_following(artist_ids: list)`

The rest are similar to the ones above. One consideration could involve the `current_user_playlists` being a part of the "Follow" API as `followed_playlists`, because the endpoint returns all your saved playlists including ones that you simply follow. That would also be in line with the idea that deleting a playlist is simply unfollowing it. With that change I would perhaps remove the prefixes from all of them.

**Comment by marioortizmanero** [comment]
Not really sure either, to be honest. I'd leave them the as similar as the official API as possible to avoid confusion. The name doesn't matter that much because after all most people usually look it up in the docs rather than with autocomplete or similars. I'd use:

1. `playlist_is_following(playlist_id, user_ids)`
2. `playlist_follow(playlist_id)`
3. `followed_artists()`
4. `artists_is_following(artist_ids: list)`

Because it makes sense to me that if you're accessing the user's followed playlists and such you'll need authorization for it. If the scopes were to be verified inside the implementation, it could work out just fine too. Although having to track changes for scope requirements in the official API could be quite annoying and troublesome too... Not sure if it's worth it.

**Comment by felix-hilden** [comment]
Yeah, I think we'll go with removing the prefixes from Follow and changing `current_user_playlists` to `followed_playlists`.

I ment the decorator would only check if it's an app or user token. But checking scopes would be the next level thing. And I think we won't add any checking for now. My initial idea at least would not allow simple string tokens. I would have checked the refresh token property.
